# This Cloud Build file builds a Docker image and runs a Python script to process CSV files.
# The script identifies modified CSV files in a GitHub commit and uploads their data to BigQuery.

# To use this Cloud Build file, you need to:
# 1. Create a Cloud Build trigger that connects to your GitHub repository.
# 2. Configure the trigger to use a GitHub App for authentication.
# 3. Create a secret in Google Secret Manager to store your GitHub App's private key.
# 4. Grant the Cloud Build service account the "Secret Manager Secret Accessor" role on the secret.
# 5. Set the following substitution variables in your trigger:
#    - _REPO_NAME: The name of your GitHub repository (e.g., "your-username/your-repo").
#    - _SECRET_NAME: The name of the secret containing your GitHub App's private key.
#    - _APP_ID: Your GitHub App's ID.
#    - _INSTALLATION_ID: The installation ID of your app on the repository.

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/csv-processor:$COMMIT_SHA'
      - '.'
    dir: 'csv_processing' # Run the build in the csv_processing directory

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/csv-processor:$COMMIT_SHA'

  # Run the CSV processing script
  - name: 'gcr.io/$PROJECT_ID/csv-processor:$COMMIT_SHA'
    id: ProcessCSV
    entrypoint: 'python'
    args:
      - 'process_csv.py'
    env:
      - 'REPO_NAME=${_REPO_NAME}'
      - 'COMMIT_SHA=${COMMIT_SHA}'
      - 'GCP_PROJECT=${PROJECT_ID}'
      - 'GITHUB_APP_ID=${_APP_ID}'
      - 'GITHUB_INSTALLATION_ID=${_INSTALLATION_ID}'
    # The GITHUB_PRIVATE_KEY will be available as an environment variable in the container.
    # You need to configure the secret in the "availableSecrets" section below.
    secretEnv: ['GITHUB_PRIVATE_KEY']

# This section makes the GitHub App private key from Secret Manager available to the build steps.
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/${_SECRET_NAME}/versions/latest
    env: 'GITHUB_PRIVATE_KEY'

# Store the image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/csv-processor:$COMMIT_SHA'
